name: CI for a Rust project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: cargo test
      - name: Lint
        run: cargo clippy -- -D warnings

  build:
    runs-on: ubuntu-latest
    needs: test-and-lint

    steps:
      - uses: actions/checkout@v4
      - name: Build in release mode
        run: cargo build --release